name: template_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_library:
    path: ../shared_library/
  freezed:
  freezed_annotation:
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0
  graphs: "2.2.0" # Important to generate the files .g.dart
  json_serializable:
  build_runner:
  injectable_generator:  

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
