name: template_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_library:
    path: ../shared_library/
  freezed:
  freezed_annotation:
  json_annotation: ^4.8.1
  retrofit: '>=4.0.0 <5.0.0'
  logger: any  #for logging purpose

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0
  graphs: "2.2.0" # Important to generate the files .g.dart
  # json_serializable:
  json_serializable: ^6.6.2
  # build_runner:
  build_runner: '>=2.3.0 <4.0.0'
  injectable_generator:  
  retrofit_generator: '>=7.0.0 <8.0.0' # required dart >=2.19

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
